version: "3.6"

services:
  example1-service:
    build: example
    ports:
      - "8080:8080"

  example2-service:
    build: example2
    ports:
      - "8081:8081"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/config.yml" ]
    volumes:
      - ./config/otel-config.yml:/etc/config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver port
      - "8889:8889" # Prometheus exporter metrics

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "14250:14250"
      - "16686:16686"
